import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {theme} from "@/theme";
import React from "react";
import {FloraGlobalStyle, FloraThemeProvider} from "bgflora/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.JSX.Element;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <FloraThemeProvider theme={theme}>
          <FloraGlobalStyle/>
          {children}
      </FloraThemeProvider>
      </body>
    </html>
  );
}
